
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
spec:
  accessModes: {{ .Values.database.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}
