apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ index .Values.ingress.paths 0 "path" }}
            pathType: {{ index .Values.ingress.paths 0 "pathType" }}
            backend:
              service:
                name: {{ index .Values.ingress.paths 0 "service" "name" }}
                port:
                  number: {{ index .Values.ingress.paths 0 "service" "port" }}
